version: '3.8'

services:
  app:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./auth_data:/app/auth_data
      - ./user_data:/app/user_data
      - ./logs:/app/logs
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - celery-worker
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  celery-worker:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./auth_data:/app/auth_data
      - ./user_data:/app/user_data
      - ./logs:/app/logs
    command: celery -A async_tasks.celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2

  celery-beat:
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./auth_data:/app/auth_data
      - ./user_data:/app/user_data
      - ./logs:/app/logs
    command: celery -A async_tasks.celery_app beat --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2

volumes:
  redis_data: